CREATE TABLE Teams (
    TeamID INT PRIMARY KEY AUTO_INCREMENT,
    TeamName VARCHAR(50) UNIQUE NOT NULL,
    TeamDepartment VARCHAR (50)
);

CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR (30) NOT NULL,
    LastName VARCHAR (50) NOT NULL,
    Email VARCHAR (50) UNIQUE NOT NULL,
    TeamID INT,
    FOREIGN KEY (TeamID) REFERENCES Teams(TeamID) ON DELETE SET NULL
);

CREATE TABLE Rooms (
    RoomID INT PRIMARY KEY AUTO_INCREMENT,
    RoomName VARCHAR (30) UNIQUE NOT NULL,
    RoomFloor INT,
    Capacity INT
);

CREATE TABLE Desks (
    DeskID INT PRIMARY KEY AUTO_INCREMENT,
    DeskName VARCHAR (30) UNIQUE NOT NULL,
    DeskFloor INT
);

CREATE TABLE Bookings (
    BookingID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    DeskID INT,
    BookingDate DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE SET NULL,
    FOREIGN KEY (DeskID) REFERENCES Desks(DeskID) ON DELETE SET NULL
);